### ISSUE TITLE
Refactor + Optimize builder scripts

### ISSUE THREAD

**Issue by flxwu** [30-seconds/30-seconds-of-interviews#106]
I'd suggest, similar to Chalarangelo/30-seconds-of-code#743 , to optimize the builder scripts by using [`markdown-builder`](https://github.com/flxwu/markdown-builder)' to make them more dynamic and readable.

**Comment by Chalarangelo** [comment]
Not a bad idea, after we finalize the builder, you can give it a spin on this repo, see how it fares and if there any major issues that need to be addressed.
