### ISSUE TITLE
New feature proposal: React Questions 

### ISSUE THREAD

**Issue by fejes713** [30-seconds/30-seconds-of-interviews#110]
### The title says it all. Our next step is adding React questions 😮 

After talking with Sudheer Jonna (@sudheerj) we agreed to add react.js questions to 30-seconds repository. 

Jonna already did 80% of the work in this repository: https://github.com/sudheerj/reactjs-interview-questions

The goal, for now, is to pick best ~25 questions from Jonna's repository and add them to our repository. All the questions are good. However, answers need a bit refactoring to match our style so the work is not just copy-paste 👍 

Let's finish this by the end of October 📆 

_TODO:_

- Update script to allow React.js questions
- React questions should have the purple gradient (@Chalarangelo 's idea)
- Add ~25 questions

**Comment by skatcat31** [comment]
For a second I was REALLY confused about this until I noticed this was interviews not code... I'm getting to tired from interviews -.-;;

**Comment by skatcat31** [comment]
I can get behind this. Tomorrow I have some raiding to do in D2 after some calls in the morning and afternoon. After that I'll start getting on which questions I think would be best to move over

**Comment by fejes713** [comment]
@skatcat31 Thank you for your time! Once you find the best ones the rest of the team and I can start implementing them 👍 

This is probably the last bigger addition to interviews codebase for this year. I have no major plans for it until 2019

**Comment by skatcat31** [comment]
I ended up having a much longer day than I planned. I'll hop on this tonight

**Comment by skatcat31** [comment]
Alrighty reading through it now and some I've recently encountered he's covered:

- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-the-difference-between-element-and-component
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-the-purpose-of-callback-function-as-an-argument-of-setstate possibly with a corollary about how you should use the life-cycle method unless this is a specific use case(firing off a request with that current state)
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-the-difference-between-html-and-react-event-handling
- [ ] https://github.com/sudheerj/reactjs-interview-questions#how-to-bind-methods-or-event-handlers-in-jsx-callbacks
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-inline-conditional-expressions
- [ ] https://github.com/sudheerj/reactjs-interview-questions#how-to-pass-a-parameter-to-an-event-handler-or-callback
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-key-and-benefit-of-using-it-in-lists
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-the-use-of-refs with a corralary of "why should you avoid refs in most cases?"
- [ ] https://github.com/sudheerj/reactjs-interview-questions#which-is-preferred-option-with-in-callback-refs-and-finddomnode
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-controlled-components
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-uncontrolled-components
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-lifting-state-up-in-reactjs
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-the-different-phases-of-reactjs-component-lifecycle
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-the-lifecycle-methods-of-reactjs
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-higher-order-components
- [ ] https://github.com/sudheerj/reactjs-interview-questions#how-to-create-props-proxy-for-hoc-component
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-children-prop
- [ ] https://github.com/sudheerj/reactjs-interview-questions#how-to-write-comments-in-reactjs
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-is-the-purpose-of-using-super-constructor-with-props-argument
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-would-be-the-common-mistake-of-function-being-called-every-time-the-component-renders
- [ ] https://github.com/sudheerj/reactjs-interview-questions#why-reactjs-uses-classname-over-class-attribute
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-fragments This is really more new tech but is something senior level developers will need to be aware of. Often it's not a deal breaker to get this wrong in the interview pre screen
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-portals-in-reactjs again advanced future tech
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-stateful-components this one is more useful over the stateless question but both might want to be considered
- [ ] https://github.com/sudheerj/reactjs-interview-questions#how-to-apply-validation-on-props-in-reactjs again more advanced testing and tooling questions but god this helps with training lower devs
- [ ] https://github.com/sudheerj/reactjs-interview-questions#what-are-error-boundaries-in-reactjs16


okay I'm gonna take a break now... ended at 54 if anyone wants to continue tonight

**Comment by fejes713** [comment]
Done 💯
