### ISSUE TITLE
Question is displayed twice in README.md

### ISSUE THREAD

**Issue by McVenco** [30-seconds/30-seconds-of-interviews#115]
The question "How can you avoid callback hells?" is displayed in both the Javascript and Node sections. Since it's a general Javascript issue it doesn't really need to be in the Node section anyway.

**Comment by skatcat31** [comment]
confirmed, it is in two areas on the readme. Will see if it's in two areas on site

**Comment by skatcat31** [comment]
It only appears once on the website. We should find a way to remove it from the duplicate section, and apply it mostly to the 'JavaScript' tag. Thanks!

**Comment by fejes713** [comment]
@flxwu is there enough room to update 30interviews to use your next-gen markdown builder?

**Comment by flxwu** [comment]
we're already using my markdown builder ^^

**Comment by fejes713** [comment]
Woah. Faaaaaantastic ❤️

**Comment by flxwu** [comment]
> It only appears once on the website. We should find a way to remove it from the duplicate section, and apply it mostly to the 'JavaScript' tag. Thanks!

We should remove the "node" tag from this snippet then I think

**Comment by Chalarangelo** [comment]
@flxwu That sounds like a bad idea, we should clean up duplicates more consistently, so that this does issue does not arise again in the future.

**Comment by flxwu** [comment]
🤔 what are you thinking of?

**Comment by Chalarangelo** [comment]
I'll have to check the scripts more thoroughly, will report back as soon as I get an idea.

**Comment by skatcat31** [comment]
Possible solution: generate a Set with snippet filenames as a way to check if a snippet has been added to the markdown before, and if so point it to the last link generated so that both can be in their sections and point to a single snippet(so a Set of fileName(sanitized for variable safety), and a link so that it points to the same generated area)

**Comment by Chalarangelo** [comment]
@skatcat31 I like this idea quite a lot.

**Comment by Chalarangelo** [comment]
This has been sitting for a while, any news or ideas?
