### ISSUE TITLE
Comment is showing on main website under 'Good to hear'

### ISSUE THREAD

**Issue by tkore** [30-seconds/30-seconds-of-interviews#133]
I was browsing through the 30secondsofinterviews.org website and noticed that in the [How to write comments in React](https://30secondsofinterviews.org/#react-comments) section, there's a malformed HTML comment that's showing in the `Good to hear` section.

I wanted to change it by opening a PR with the [file on GitHub](https://github.com/30-seconds/30-seconds-of-interviews/blob/28a0112012e54be2d2167d2a9bbd7ee3bd8d2d92/questions/react-comments.md) but then noticed the error doesn't exist there.

Just a heads up :)

![image](https://user-images.githubusercontent.com/4380333/49691797-06d0ba80-fb53-11e8-8e68-656c05e69dbd.png)

**Comment by flxwu** [comment]
Hey, thanks for noting! We've fixed it :)
