### ISSUE TITLE
update stateful-components.md

### ISSUE THREAD

**Issue by kamilluc** [30-seconds/30-seconds-of-interviews#135]
react 16.7 (currently in alpha) introduced hooks, which allows to use state in non-class components
resource: https://reactjs.org/docs/hooks-intro.html

**Comment by skatcat31** [comment]
It looks like this will be coming to React soon

**Comment by fejes713** [comment]
@skatcat31 yep, Dan said they're working on it and it's going to ship very soon.

**Comment by skatcat31** [comment]
I've been using React with TS recently so I haven't really looked at this in awhile. If this is the case this may be faster than using a class, which could be nice

**Comment by Chalarangelo** [comment]
Let's wait until hooks are released in a stable version first, before changing this, right?

**Comment by fejes713** [comment]
Hooks are stable now (as far as I know). 

If anybody is interested in picking up this (or you @kamilluc ), it's a good first issue 👍 You can find the contributor guidelines [here](https://github.com/30-seconds/30-seconds-of-interviews/blob/master/CONTRIBUTING.md). 

Let me know if you need any help, I'll be willing to help

**Comment by kamilluc** [comment]
@atomiks updated 'stateful-components' half a year ago. You can close issue.
#144

**Comment by fejes713** [comment]
Oh, haha. Thanks for making it clear.
