### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by asap** [30-seconds/30-seconds-of-interviews#142]
Found a typo here:

https://github.com/30-seconds/30-seconds-of-interviews/blob/28a0112012e54be2d2167d2a9bbd7ee3bd8d2d92/questions/fragments.md

Can I fix?

**Comment by Chalarangelo** [comment]
@asap Definitely, please submit a PR to this repo and we'll merge it right away!

**Comment by asap** [comment]
Here's the PR: https://github.com/asap/30-seconds-of-interviews/pull/1

**Comment by asap** [comment]
Here's the PR. This project is a lifesaver for me so I'm happy to help and contribute, even in this small way!
