### ISSUE TITLE
Accessibility questions

### ISSUE THREAD

**Issue by fejes713** [30-seconds/30-seconds-of-interviews#172]
[Here](https://scottaohara.github.io/accessibility_interview_questions/)'s the list of good accessibility questions that we could add. Only answers are needed 😉 

I'd suggest this be a task for Hacktoberfest this year. 

Let me know if you need any help with first-time contributions 👍 I'd be happy to help! :octocat: 

For more info follow our [contributing](https://github.com/30-seconds/30-seconds-of-interviews/blob/master/CONTRIBUTING.md) guidelines.

**Comment by CharaeKeow** [comment]
Would like to work on this but I'm not sure how can I help. Could you enlighten me a bit? Thanks!

**Comment by fejes713** [comment]
Sure @CharaeKeow! :octocat: 

We collect all questions under `./questions` directory. Every question has the same format that you can find [here](https://github.com/30-seconds/30-seconds-of-interviews/blob/master/question-template.md). Keep in mind that you should select `raw` option on GitHub, or open that file with your editor in order to see the actual content.

You can add your own questions with answers to the `./questions` directory and tag them with `accessibility` tag. To see how we did it for other categories, take a look at any random questions from `./questions`.

Right now, once you add the `accessibility` questions they won't be live. Once we collect 5 or more accessibility question, I'll add the support for accessibility category on the website.

Hope that makes sense 👍 If not, feel free to ask anything that wasn't clear.

**Comment by aitchiss** [comment]
If you're still looking for help I'd love to help with this - would you be happy for me to submit a PR for the technical questions/answers?

Then if anyone else is still keen to help we could divide and conquer 😁

**Comment by fejes713** [comment]
Hey @aitchiss, yes we're looking for help with this. Thank you so much! Feel free to add any questions you like! 👍 

Please let me know if you need any help or guidance with contributing! I'd be happy to help.

**Comment by digilou** [comment]
This is a great idea. Still need more questions?

**Comment by fejes713** [comment]
@digilou yeah! As far as I see nobody contributed any accessibility questions + answers yet. Feel free to contribute if you have time and willpower to do so 😄 

Let me know if you need any help with contributing. :octocat:

**Comment by fejes713** [comment]
This is an ongoing issue so I am going to keep it open.

**Comment by skatcat31** [comment]
@fejes713 you closed this again

**Comment by fejes713** [comment]
Haha, sorry. The auto-close feature is nice in most cases, but for this issue, it's not at all.
