### ISSUE TITLE
The answer to the "What are JavaScript data types?" question is no longer correct

### ISSUE THREAD

**Issue by yatoogamii** [30-seconds/30-seconds-of-interviews#197]
The answer to the ["What are JavaScript data types?"](https://github.com/30-seconds/30-seconds-of-interviews/blob/master/questions/types.md) question is no longer correct

Because now we have 7 primitives data types (String, Number, BigInt, Boolean, Null, Undefined, Symbol) and 1 non-primitive data type (object)

Can I fix?

links :
https://tc39.es/ecma262/#sec-ecmascript-language-types
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

**Comment by fejes713** [comment]
Hey @yatoogamii 👋 

Thanks for noticing this! Yeah, definitely, you can fix this. We would appreciate it very much 😄 

You can just update the file you mentioned and the website will be built and deployed automatically.
