### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by LinDaiDai** [30-seconds/30-seconds-of-interviews#199]
Hi, writer. First of all, thank you for your good questions and good answers. Secondly, I hope to quote some of your title in my article, but I will rewrite the answer with my own understanding, and will indicate the source of the title, such as this article: [https://juejin.im/post/5edd051051882543306824a3#heading-3](https://juejin.im/post/5edd051051882543306824a3#heading-3) Is this ok? If you feel offended, I will correct it immediately. Thank you.😊

**Comment by fejes713** [comment]
Hey sorry for this mega late reply! Thanks for linking to the source, the article looks great!
