### ISSUE TITLE
Parcel hot reloading problems

### ISSUE THREAD

**Issue by atomiks** [30-seconds/30-seconds-of-interviews#54]
When the file is saved in a text editor the page is hot-reloaded to preserve Hyperapp's state and the console comes up with a bunch of errors and a bunch of elements don't get rendered. I've had similar problems in multiple different projects and I'm not sure why.

@flxwu any help?

**Comment by fejes713** [comment]
@atomiks any news regarding this problem?

**Comment by jorgebucaran** [comment]
Could this be related to https://github.com/hyperapp/hyperapp/issues/705?

**Comment by fejes713** [comment]
@jorgebucaran thanks! @atomiks can check on this one so we can close this issue?

**Comment by jorgebucaran** [comment]
@fejes713 https://github.com/hyperapp/hyperapp/issues/705#issuecomment-399278416 was closed as per that comment. I've not had much trouble with Parcel recently, but I still have to restart it from scratch from time to time.

**Comment by Chalarangelo** [comment]
For what it's worth, most of the trouble I've had with Hyperapp and Parcel comes from the `.cache` directory messing up stuff. Try adding the proper flag for ignoring that folder and see what result you get.

**Comment by fejes713** [comment]
@atomiks can we close this? Seems like the website is stable and I had no issues with this since then.

**Comment by skatcat31** [comment]
closing due to age and lack of repeatable creation of issue.
